### ISSUE TITLE
tensorframes is not working with variables.

### ISSUE THREAD

**Issue by yupbank** [databricks/tensorframes#106]
```
data = [Row(x=float(x)) for x in range(5)]
df = sqlContext.createDataFrame(data)
with tf.Graph().as_default() as g:
    # The placeholder that corresponds to column 'x'
    x = tf.placeholder(tf.double, shape=[None], name="x")
    # The output that adds 3 to x
    b = tf.Variable(float(3), name='a', dtype=tf.double)
    z = tf.add(x, b, name='z')
    #with or without `sess.run(tf.global_variables_initializer())`  following will fail
    
    df2 = tfs.map_blocks(z, df)

df2.show()
```

**Comment by yupbank** [comment]
it's kind of interesting that, if change b into
```
b = tf.assign( tf.Variable(float(0), name='a', dtype=tf.double), 3.0)
```
it would work

**Comment by thunterdb** [comment]
Interesting, I have not tried to use variables before. I will see what is possible in that respect.

**Comment by yupbank** [comment]
basically, tensorframes is so greedy for tensorflow session any execution relate to session can not being processed in python land.. i am not sure how to manage that though..

**Comment by yupbank** [comment]
so the work around would be use a session to do the job and assign a mirror variable initialized with session to the variable we need to avoid the session needed scenario.

**Comment by yupbank** [comment]
what do you say if we make a local session to ensure all the variables are initialized and  `graph_util.convert_variables_to_constants`

before we add the graph to builder https://github.com/databricks/tensorframes/blob/master/src/main/python/tensorframes/core.py#L38 ?

**Comment by thunterdb** [comment]
After looking at the documentation, yes, this seems to be the recommended way. The only downside I could see is that the graph that gets serialized may have some large embedded constants. This is fine as a start.

**Comment by yupbank** [comment]
now it's supported..
