### ISSUE TITLE
kmeans.py should be updated with tensorflow-1.x+

### ISSUE THREAD

**Issue by taklwu** [databricks/tensorframes#116]
I recently ran into this kmeans example on tensorflow-1.2.1 and found several APIs have changed in Tensorflow, mostly tf.pack() -> tf.stack. 

Is tensorframes going to support tensorflow-1.x+?

**Comment by thunterdb** [comment]
@taklwu thank you for reporting this issue. Indeed, there has been some changes in the TensorFlow API, it is time for a new release.

**Comment by taklwu** [comment]
it's been a while, so, resolve this issue
