### ISSUE TITLE
Support pandas dataframe as input

### ISSUE THREAD

**Issue by thunterdb** [databricks/tensorframes#32]
Letting a pandas dataframes as an input simplifies the debugging, and provides a simple (non-distributed implementation).

For this task, all the tensorframe python API should support the `df` argument being a pandas dataframe, and should use the python tensorflow package instead of passing it to java. This should be a simple wrapper around creating a new TF session, running it and returning the result values.

**Comment by yupbank** [comment]
is this yet being developed ? would like to help

**Comment by thunterdb** [comment]
@yupbank this is not being developed. If you want to help out, you are more than welcome! I think the best place to start looking is by adding support for mapping rows in this file:

https://github.com/databricks/tensorframes/blob/master/src/main/python/tensorframes/core.py#L175

Let me know if you have some questions.

**Comment by yupbank** [comment]
yeah, there is some attempt for supporting from tensorflow though 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/dataframe/dataframe.py
