### ISSUE TITLE
Does not work with Python3

### ISSUE THREAD

**Issue by ushnish** [databricks/tensorframes#57]
I just started using this with Python3, these are my commands run and the output messages.

`$SPARK_HOME/bin/pyspark --packages databricks:tensorframes:0.2.3-s_2.10`

> Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
> [GCC 4.9.2] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> Ivy Default Cache set to: /root/.ivy2/cache
> The jars for the packages stored in: /root/.ivy2/jars
> :: loading settings :: url = jar:file:/opt/spark-1.5.2/assembly/target/scala-2.10/spark-assembly-1.5.2-hadoop2.2.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
> databricks#tensorframes added as a dependency
> :: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
>     confs: [default]
>     found databricks#tensorframes;0.2.3-s_2.10 in spark-packages
>     found org.apache.commons#commons-lang3;3.4 in central
> :: resolution report :: resolve 98ms :: artifacts dl 4ms
>     :: modules in use:
>     databricks#tensorframes;0.2.3-s_2.10 from spark-packages in [default]
>     org.apache.commons#commons-lang3;3.4 from central in [default]
>     ---------------------------------------------------------------------
>     |                  |            modules            ||   artifacts   |
>     |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
>     ---------------------------------------------------------------------
>     |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
>     ---------------------------------------------------------------------
> :: retrieving :: org.apache.spark#spark-submit-parent
>     confs: [default]
>     0 artifacts copied, 2 already retrieved (0kB/3ms)
> Welcome to
>       ____              __
>      / **/**  ___ _____/ /__
>     _\ \/ _ \/ _ `/ __/  '_/
>    /__ / .__/_,_/_/ /_/\_\   version 1.5.2
>       /_/
> 
> Using Python version 3.4.3 (default, Mar 26 2015 22:03:40)
> SparkContext available as sc, SQLContext available as sqlContext.

`import tensorflow as tf`
`import tensorframes as tfs`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/tmp/spark-349c9955-ccd8-4fcd-938a-7e719fc45653/userFiles-bb935142-224f-4238-a144-f1cece7a5aa2/databricks_tensorframes-0.2.3-s_2.10.jar/tensorframes/**init**.py", line 36, in <module>
> **ImportError: No module named 'core'**

**Comment by nchammas** [comment]
Yeah, when I read this line in the README

>  Python 3+ should work but it has not been tested.

I was skeptical because it appears that no Spark packages can even be built with Python 3 support in the first place: https://github.com/databricks/sbt-spark-package/issues/26

**Comment by mariusvniekerk** [comment]
#60 should fix this

**Comment by siebertlooije** [comment]
Hi,

I am trying to use the tensorframes in a jupyter notebook with python 3. But I am receiving the import problems that are specified before :

ImportError                               Traceback (most recent call last)
<ipython-input-1-4798ad5f3b2e> in <module>()
      1 import tensorflow as tf
----> 2 import tensorframes as tfs
      3 from pyspark.sql import Row
      4 
      5 data = [Row(x=float(x)) for x in range(10)]

/werk/tensorframes/target/scala-2.11/tensorframes-assembly-0.2.4.jar/tensorframes/__init__.py in <module>()
     34 __version__ = "2.0.0"
     35 
---> 36 from core import *

ImportError: No module named 'core'

The steps I did was:

- Pulled the tensorframe from : https://github.com/databricks/tensorframes
- Build the tensorframe with the build/sbt assembly and build/sbt tfPackage like in the github.
- Then I added the jar to my pythonpath by export `PYTHONPATH=/way/to/target/scala-2.10/tensorframes-assembly-0.2.4.jar' 
- Setup my jupyter notebook config by : 
export PYSPARK_PYTHON=/usr/bin/python3
export PYSPARK_DRIVER_PYTHON=/way/to/anaconda3/bin/jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook --no-browser --port=8888'

- At last I runned the pyspark in the terminal with :  pyspark --jars way/to/target/scala-2.11/tensorframes-assembly-0.2.4.jar

Am I doing something wrong or is the bug not yet fixed ? 

Thanks

**Comment by mariusvniekerk** [comment]
PR #60 is still open.  You can build from source if you want python 3.  Not sure when it'll get merged in.

**Comment by siebertlooije** [comment]
@mariusvniekerk thanks for the response. By building from source you mean the build/sbt assembly and build/sbt tfPackage right ? Even that does not work at the moment.

**Comment by thunterdb** [comment]
I just merged #69 which includes @mariusvniekerk 's fixes. I will make a release at some point next week. @siebertlooije if you have some issues, you can take a look at the `.travis.yml` file, which contains the commands run by continuous integration to test python 3.
