### ISSUE TITLE
Can not import tensorframes

### ISSUE THREAD

**Issue by sergulaydore** [databricks/tensorframes#59]
Hi,

I am trying to load tensorframes from databricks using the following script but could not succeed so far. Can you please let me know what I am doing wrong?

`import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.databricks:tensorframes:0.2.3-s_2.10 pyspark-shell'

import pyspark
try:
    import tensorflow as tf
    import tensorframes as tfs
    print("Tensorframes successfully imported")
except:
    print("Failed to import tensorframes")
`

**Comment by felixcheung** [comment]
I think to load a Spark package from within Databricks there is a menu option

**Comment by thunterdb** [comment]
@sergulaydore you should be able to use tensorflatmes as a regular library in databricks, see this page: https://docs.databricks.com/user-guide/libraries.html

I am going to close this ticket for now, but let me know if you still encounter some issues.
