### ISSUE TITLE
Running Second README.md example (block-wise reducing operations) fails with `java.lang.AssertionError: assertion failed: NodeDef mentions attr &apos;Tidx&apos;`

### ISSUE THREAD

**Issue by dennyglee** [databricks/tensorframes#65]
While the first example worked, the second example on block-wise reducing operations failed.  The code snippet:

```
with tf.Graph().as_default() as g:
    # The placeholders. Note the special name that end with '_input':
    y_input = tfs.block(df3, 'y', tf_name="y_input")
    z_input = tfs.block(df3, 'z', tf_name="z_input")
    y = tf.reduce_sum(y_input, [0], name='y')
    z = tf.reduce_min(z_input, [0], name='z')
    # The resulting dataframe
    (data_sum, data_min) = tfs.reduce_blocks([y, z], df3)

# The final results are numpy arrays:
print data_sum
# [45.0, -45.0]
print data_min
# [0.0, -9.0]
```

results in the error:

`Py4JJavaError: An error occurred while calling o2619.buildRow. : java.lang.AssertionError: assertion failed: NodeDef mentions attr 'Tidx' not in Op<name=Sum; signature=input:T, reduction_indices:int32 -> output:T; attr=keep_dims:bool,default=false; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT64, DT_INT32, DT_UINT8, DT_UINT16, DT_INT16, DT_INT8, DT_COMPLEX64, DT_COMPLEX128, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF]>; NodeDef: y = Sum[T=DT_DOUBLE, Tidx=DT_INT32, keep_dims=false](y_input, y/reduction_indices) at scala.Predef$.assert(Predef.scala:179) at org.tensorframes.impl.TensorFlowOps$$anonfun$analyzeGraph$4.apply(TensorFlowOps.scala:100) at org.tensorframes.impl.TensorFlowOps$$anonfun$analyzeGraph$4.apply(TensorFlowOps.scala:97) at org.tensorframes.impl.TensorFlowOps$.withSession(TensorFlowOps.scala:58) at org.tensorframes.impl.TensorFlowOps$.analyzeGraph(TensorFlowOps.scala:97) at org.tensorframes.impl.SchemaTransforms$class.reduceBlocksSchema(DebugRowOps.scala:81) at org.tensorframes.impl.SchemaTransforms$.reduceBlocksSchema(DebugRowOps.scala:272) at org.tensorframes.impl.PythonOpBuilder.buildRow(PythonInterface.scala:112) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) at py4j.Gateway.invoke(Gateway.java:259) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:209) at java.lang.Thread.run(Thread.java:745) 
`

**Comment by dennyglee** [comment]
Oh, I just realized that this is happening when I'm working with TensorFlow 0.12; if I use TensorFlow 0.9, the example works.

**Comment by thunterdb** [comment]
I will bump the embedded version of tensorflow with the 0.2.5 release.
