### ISSUE TITLE
Embed a more recent version of tensorflow

### ISSUE THREAD

**Issue by thunterdb** [databricks/tensorframes#70]
TFrames should embed the latest release from javacpp.

**Comment by felixcheung** [comment]
https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0-rc0 is the latest as of now

**Comment by thunterdb** [comment]
the master branch has support for v1.0.1. I am going to wait for a new official release of javacpp-tensorflow before making a new artifact.

**Comment by thunterdb** [comment]
A new release has been pushed out, with TF 1.0.1.
