### ISSUE TITLE
Add support for Spark 2.1.0

### ISSUE THREAD

**Issue by felixcheung** [databricks/tensorframes#71]

**Comment by felixcheung** [comment]
Actually, it looks like it was changed to 2.1.0 about 12 days ago: https://github.com/databricks/tensorframes/commit/c3fdc10251debc27d5b83ecb80edf85e97494ea7

So perhaps we are good then? Or we should have simultaneous support for 2.1 and 2.0?

**Comment by felixcheung** [comment]
Or just update the https://github.com/databricks/tensorframes/blob/master/README.md

**Comment by thunterdb** [comment]
@felixcheung do you have a specific need for spark 2.0? I feel it is going to be hard enough to support a matrix of python2/3 + scala 2.10/2.11, so unless there is a specific request, it is easier to focus on the recent version. Can you send a PR to update the doc?

**Comment by felixcheung** [comment]
I feel there are many distributions out there that are not running the latest and greatest, so perhaps it would be a good idea to test against 2.0 still in the mean time? From the look of it, it doesn't like we need any code change to support 2.0 & 2.1?

**Comment by thunterdb** [comment]
@felixcheung I have tried out the latest release on Spark 2.0.2, and it seems to work. It is also now tested by travis. I am going to close this ticket, but please open a ticket if you experience some issues.
