### ISSUE TITLE
Scala example does not work

### ISSUE THREAD

**Issue by nicodri** [databricks/tensorframes#86]
I'm having trouble running the provided Scala example in the spark shell.

My local environment is:
* Spark 2.1.0
* Scala version 2.11.8 
* Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121

I ran the spark-shell with:
`spark-shell --packages databricks:tensorframes:0.2.5-rc2-s_2.11`

I get the following stacktrace which shuts down my spark process:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff90451b52, pid=64869, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsystem_c.dylib+0x1b52]  strlen+0x12
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/ndrizard/projects/temps/hs_err_pid64869.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Thanks for your help!

**Comment by thunterdb** [comment]
@nicodri I see that you are using macos. It turns out that tensorflow as currently packaged may crash on some configurations. It is unclear which ones seem to work, see the thread in https://github.com/bytedeco/javacpp-presets/issues/396

This should be solved by using the official tensorflow bindings (issue #76), which I expect to have in the next release. In the meantime, there should be no problem in docker or in linux.

**Comment by nicodri** [comment]
Ok that makes sense @thunterdb, thanks for the quick answer. Do you have an ETA of the next release?

**Comment by thunterdb** [comment]
I hope to have a release candidate in the next month. Most of the work is going to happen in this branch if you want to track the progress: https://github.com/databricks/tensorframes/pull/87

**Comment by thunterdb** [comment]
@nicodri if you are willing to try to compile tensorframes yourself, the fix has been merged (tested on my macbook).

**Comment by nicodri** [comment]
Thank you for the update @thunterdb. The scala example worked smoothly locally on mac!
